Fixed memory leak in UDP_Socket observable
alexander-smoktal/rx-pipeline pull request #4
Opened 2016-12-19 17:15 UTC by vni

2016-12-19 17:44 UTC, alexander-smoktal requested changes
Please fix curly braces and observable_broadcast

2016-12-19 17:44 UTC, alexander-smoktal commented on src/main.c
> +    if (data && data != end_of_data())
Please add curly braces for condition body

2016-12-19 17:44 UTC, alexander-smoktal commented on src/observables/observable_udp_socket.c
> +    if (nread == 0 && addr != NULL) { // an empty frame received
Wont this will be cleaner to use inside nread ==0 branch for both "addr == and != NULL"?
Also please try to start comment from capital letter.

2016-12-19 17:44 UTC, alexander-smoktal commented on src/observables/observable_udp_socket.c
> +        if (data) {
'observable_broadcast' itself checks if data non-NULL

2016-12-19 17:44 UTC, alexander-smoktal commented on src/observables/observable_udp_socket.c
> +    if (buf->base)
Same with curly braces. We always should try to use condition body to avoid heisenbugs.

2016-12-20 08:35 UTC, vni commented
Hi!

Have fixed the code as you asked.
Also have incorporated new commit from you.

2016-12-20 10:48 UTC, merged